/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sritel.billing.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StatementRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9119002316578183554L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StatementRecord\",\"namespace\":\"com.sritel.billing.event\",\"fields\":[{\"name\":\"paymentDate\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StatementRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StatementRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StatementRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StatementRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StatementRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StatementRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StatementRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StatementRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StatementRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence paymentDate;
  private double amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StatementRecord() {}

  /**
   * All-args constructor.
   * @param paymentDate The new value for paymentDate
   * @param amount The new value for amount
   */
  public StatementRecord(java.lang.CharSequence paymentDate, java.lang.Double amount) {
    this.paymentDate = paymentDate;
    this.amount = amount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentDate;
    case 1: return amount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentDate = (java.lang.CharSequence)value$; break;
    case 1: amount = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentDate' field.
   * @return The value of the 'paymentDate' field.
   */
  public java.lang.CharSequence getPaymentDate() {
    return paymentDate;
  }


  /**
   * Sets the value of the 'paymentDate' field.
   * @param value the value to set.
   */
  public void setPaymentDate(java.lang.CharSequence value) {
    this.paymentDate = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Creates a new StatementRecord RecordBuilder.
   * @return A new StatementRecord RecordBuilder
   */
  public static com.sritel.billing.event.StatementRecord.Builder newBuilder() {
    return new com.sritel.billing.event.StatementRecord.Builder();
  }

  /**
   * Creates a new StatementRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StatementRecord RecordBuilder
   */
  public static com.sritel.billing.event.StatementRecord.Builder newBuilder(com.sritel.billing.event.StatementRecord.Builder other) {
    if (other == null) {
      return new com.sritel.billing.event.StatementRecord.Builder();
    } else {
      return new com.sritel.billing.event.StatementRecord.Builder(other);
    }
  }

  /**
   * Creates a new StatementRecord RecordBuilder by copying an existing StatementRecord instance.
   * @param other The existing instance to copy.
   * @return A new StatementRecord RecordBuilder
   */
  public static com.sritel.billing.event.StatementRecord.Builder newBuilder(com.sritel.billing.event.StatementRecord other) {
    if (other == null) {
      return new com.sritel.billing.event.StatementRecord.Builder();
    } else {
      return new com.sritel.billing.event.StatementRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for StatementRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StatementRecord>
    implements org.apache.avro.data.RecordBuilder<StatementRecord> {

    private java.lang.CharSequence paymentDate;
    private double amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sritel.billing.event.StatementRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentDate)) {
        this.paymentDate = data().deepCopy(fields()[0].schema(), other.paymentDate);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing StatementRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sritel.billing.event.StatementRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentDate)) {
        this.paymentDate = data().deepCopy(fields()[0].schema(), other.paymentDate);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'paymentDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentDate() {
      return paymentDate;
    }


    /**
      * Sets the value of the 'paymentDate' field.
      * @param value The value of 'paymentDate'.
      * @return This builder.
      */
    public com.sritel.billing.event.StatementRecord.Builder setPaymentDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.paymentDate = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentDate' field has been set.
      * @return True if the 'paymentDate' field has been set, false otherwise.
      */
    public boolean hasPaymentDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentDate' field.
      * @return This builder.
      */
    public com.sritel.billing.event.StatementRecord.Builder clearPaymentDate() {
      paymentDate = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.sritel.billing.event.StatementRecord.Builder setAmount(double value) {
      validate(fields()[1], value);
      this.amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.sritel.billing.event.StatementRecord.Builder clearAmount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StatementRecord build() {
      try {
        StatementRecord record = new StatementRecord();
        record.paymentDate = fieldSetFlags()[0] ? this.paymentDate : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.amount = fieldSetFlags()[1] ? this.amount : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StatementRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<StatementRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StatementRecord>
    READER$ = (org.apache.avro.io.DatumReader<StatementRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentDate);

    out.writeDouble(this.amount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentDate = in.readString(this.paymentDate instanceof Utf8 ? (Utf8)this.paymentDate : null);

      this.amount = in.readDouble();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentDate = in.readString(this.paymentDate instanceof Utf8 ? (Utf8)this.paymentDate : null);
          break;

        case 1:
          this.amount = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










